// Mocks generated by Mockito 5.4.6 from annotations
// in storytales/test/profile_feature_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:logging/logging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:storytales/core/services/logging/logging_service.dart' as _i7;
import 'package:storytales/features/profile/domain/entities/registration_request.dart'
    as _i3;
import 'package:storytales/features/profile/domain/entities/user_profile.dart'
    as _i2;
import 'package:storytales/features/profile/domain/repositories/profile_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegistrationResponse_1 extends _i1.SmartFake
    implements _i3.RegistrationResponse {
  _FakeRegistrationResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_2 extends _i1.SmartFake implements _i4.Logger {
  _FakeLogger_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i5.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserProfile> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i6.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#getCurrentUserProfile, []),
              ),
            ),
          )
          as _i6.Future<_i2.UserProfile>);

  @override
  _i6.Future<_i2.UserProfile> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i6.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#updateDisplayName, [displayName]),
              ),
            ),
          )
          as _i6.Future<_i2.UserProfile>);

  @override
  _i6.Future<_i3.RegistrationResponse> registerUser({
    required String? email,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [], {
              #email: email,
              #displayName: displayName,
            }),
            returnValue: _i6.Future<_i3.RegistrationResponse>.value(
              _FakeRegistrationResponse_1(
                this,
                Invocation.method(#registerUser, [], {
                  #email: email,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.RegistrationResponse>);

  @override
  _i6.Future<_i2.UserProfile> verifyRegistration({required String? otpCode}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyRegistration, [], {#otpCode: otpCode}),
            returnValue: _i6.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#verifyRegistration, [], {#otpCode: otpCode}),
              ),
            ),
          )
          as _i6.Future<_i2.UserProfile>);

  @override
  _i6.Future<_i3.RegistrationResponse> loginUser({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [], {#email: email}),
            returnValue: _i6.Future<_i3.RegistrationResponse>.value(
              _FakeRegistrationResponse_1(
                this,
                Invocation.method(#loginUser, [], {#email: email}),
              ),
            ),
          )
          as _i6.Future<_i3.RegistrationResponse>);

  @override
  _i6.Future<_i2.UserProfile> verifyLogin({
    required String? sessionId,
    required String? otpCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyLogin, [], {
              #sessionId: sessionId,
              #otpCode: otpCode,
            }),
            returnValue: _i6.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#verifyLogin, [], {
                  #sessionId: sessionId,
                  #otpCode: otpCode,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UserProfile>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.UserProfile> refreshUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserProfile, []),
            returnValue: _i6.Future<_i2.UserProfile>.value(
              _FakeUserProfile_0(
                this,
                Invocation.method(#refreshUserProfile, []),
              ),
            ),
          )
          as _i6.Future<_i2.UserProfile>);
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i7.LoggingService {
  MockLoggingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Logger getLogger(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getLogger, [name]),
            returnValue: _FakeLogger_2(
              this,
              Invocation.method(#getLogger, [name]),
            ),
          )
          as _i4.Logger);

  @override
  void debug(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#info, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void error(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#error, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );
}
