// Mocks generated by Mockito 5.4.6 from annotations
// in storytales/test/story_generation_timing_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:storytales/features/library/domain/entities/story.dart' as _i2;
import 'package:storytales/features/story_generation/domain/repositories/story_generation_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStory_0 extends _i1.SmartFake implements _i2.Story {
  _FakeStory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StoryGenerationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryGenerationRepository extends _i1.Mock
    implements _i3.StoryGenerationRepository {
  MockStoryGenerationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> canGenerateStory() =>
      (super.noSuchMethod(
            Invocation.method(#canGenerateStory, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Story> generateStory({
    required String? prompt,
    String? ageRange,
    String? theme,
    String? genre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateStory, [], {
              #prompt: prompt,
              #ageRange: ageRange,
              #theme: theme,
              #genre: genre,
            }),
            returnValue: _i4.Future<_i2.Story>.value(
              _FakeStory_0(
                this,
                Invocation.method(#generateStory, [], {
                  #prompt: prompt,
                  #ageRange: ageRange,
                  #theme: theme,
                  #genre: genre,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Story>);

  @override
  _i4.Future<int> getFreeStoriesRemaining() =>
      (super.noSuchMethod(
            Invocation.method(#getFreeStoriesRemaining, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
