name: storytales
description: "AI-powered storytelling app for children"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Networking
  dio: ^5.4.1
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.3.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  # Note: firebase_dynamic_links is discontinued, using app_links instead
  app_links: ^6.4.0

  # In-app purchases
  in_app_purchase: ^3.1.13

  # Authentication & User Management
  device_info_plus: ^11.5.0
  crypto: ^3.0.3

  # Utilities
  uuid: ^4.3.3
  intl: ^0.20.2
  get_it: ^8.0.3
  logging: ^1.2.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/storybook-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/storybook-logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/logo/
    - assets/config/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
