// File generated by FlutterFire CLI.
// Contains configuration options for Firebase.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create a Linux app in the Firebase Console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // The values below are placeholders and should be replaced with actual values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFu3eHHvzYIkQuRBH9eX05kX7fVphYk90',
    appId: '1:746576505180:android:e6d4d2200c080754f87999',
    messagingSenderId: '746576505180',
    projectId: 'storytales-21ccd',
    storageBucket: 'storytales-21ccd.firebasestorage.app',
  );

  // from your Firebase project configuration files.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBNsxJCCeB2HYmPixz8NA71c-PQBqEfhY',
    appId: '1:746576505180:ios:a334c172dedf5c76f87999',
    messagingSenderId: '746576505180',
    projectId: 'storytales-21ccd',
    storageBucket: 'storytales-21ccd.firebasestorage.app',
    iosBundleId: 'com.storytales.storytales',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxU3LkwWigsLf0EqsND9Y9z5jSVr0R_6Q',
    appId: '1:746576505180:web:6ceda1ea18223f14f87999',
    messagingSenderId: '746576505180',
    projectId: 'storytales-21ccd',
    authDomain: 'storytales-21ccd.firebaseapp.com',
    storageBucket: 'storytales-21ccd.firebasestorage.app',
    measurementId: 'G-Z4F19R1YY9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBNsxJCCeB2HYmPixz8NA71c-PQBqEfhY',
    appId: '1:746576505180:ios:a334c172dedf5c76f87999',
    messagingSenderId: '746576505180',
    projectId: 'storytales-21ccd',
    storageBucket: 'storytales-21ccd.firebasestorage.app',
    iosBundleId: 'com.storytales.storytales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxU3LkwWigsLf0EqsND9Y9z5jSVr0R_6Q',
    appId: '1:746576505180:web:dd2ffa4ad0ec0073f87999',
    messagingSenderId: '746576505180',
    projectId: 'storytales-21ccd',
    authDomain: 'storytales-21ccd.firebaseapp.com',
    storageBucket: 'storytales-21ccd.firebasestorage.app',
    measurementId: 'G-N9EN1J2GR4',
  );

}